runtime: python37
env: standard
entrypoint: waitress-serve api:app

automatic_scaling:
  target_cpu_utilization: 0.9
  max_instances: 1
  max_pending_latency: 5000ms
  max_concurrent_requests: 50

# beta_settings:
#   cloud_sql_instances: bryrachrsvp:asia-southeast1:weddingrsvp=tcp:5432